version: '3.8'

services:
  trans_db:
    image: postgres:13
    volumes:
      - db2-volume:/app/data
    environment:
      POSTGRES_DB: bbdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  db2:
    image: postgres:13
    volumes:
      - db2-volume:/app/data
    environment:
      POSTGRES_DB: bbdb2
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  datacollector:
    build: .
    depends_on:
      - trans_db
      - db2

volumes:
  db1-volume:
  db2-volume:


